image: node:lts-stretch

pipelines:
  default:
    - step:
        name: Build & Package
        script:
          - npm install
          - npm run compile
          - mkdir _TMP_DEB
          - mkdir _TMP_DEB/opt
          - mkdir _TMP_DEB/opt/node-scheduler
          - cp -r ./jobs-available _TMP_DEB/opt/node-scheduler
          - cp -r ./jobs-enabled _TMP_DEB/opt/node-scheduler
          - cp -r ./lib _TMP_DEB/opt/node-scheduler
          - cp -r ./DEBIAN _TMP_DEB/
          - chmod a+x _TMP_DEB/DEBIAN/control
          - dpkg-deb --build _TMP_DEB
        artifacts:
          - ./*.deb
