pipelines:
  default:
    - step:
        image: node:lts-stretch
        name: Build & Package
        script:
          - apt-get update && apt-get install -y zip
          - ./build.sh
        artifacts:
          - node-scheduler.deb
          - node-scheduler.zip
